### ISSUE TITLE
P2P Technology

### ISSUE THREAD

**Issue by pcfreak30** [braidpool/braidpool#63]
While I am an outsider, especially in Bitcoin culture specifically, I am leaving these suggestions here if they help, as you have no Discord or other contact I know about.

I suggest you leverage existing P2P technology efforts to build on. Here is a list with rust support:

- https://github.com/libp2p/rust-libp2p | LibP2P
- https://github.com/datrs/ | Hypercore/Dat Rust port. (my project uses this for its needs).
- https://github.com/n0-computer/iroh, https://www.dumbpipe.dev | Iroh | Born out of the IPFS ecosystem, borrowing from hyper and libp2p.
- BitTorrent itself, though my research suggests encryption could be better.

One of these DHT/UDP-based protocol systems can assist you on the low level. Hypercore has its version of a P2P blockchain, though, that would need to be extended if you wanted to use it in a DAG or more complicated structures.

Anyway, I hope this helps you understand where to go to solve the legos Braidpool needs.

Kudos!

**Comment by mcelrath** [comment]
For future reference please see PR #57 with some exploratory code and further discussion of a number of libraries and approaches including QUIC.

**Comment by plebhash** [comment]
@pcfreak30 there's a public chatroom over Matrix: [https://matrix.to/#/#braidpool:matrix.org](https://matrix.to/#/#braidpool:matrix.org)

**Comment by plebhash** [comment]
there's also a discussion about this topic started here: https://github.com/braidpool/braidpool/discussions/65

**Comment by mcelrath** [comment]
I'm going to close this in favor of #65. Please continue discussing there. 

We know we need P2P and happy to have your contributions @pcfreak30, I'm just trying to help organize the repo. We don't want 1000 overlapping "issues".
