### ISSUE TITLE
FAST SubPool with 254 hasher locations

### ISSUE THREAD

**Issue by s2dd** [braidpool/braidpool#64]
One can imagine a subpool that clusters with same `ip/24` range at a datacenter.
Each hasher-location has a VPS with datacenter and tunnel into from hasher-location.
Now the share exchange 'gossips' within subpool will be very quick (µs).

Brings up questions around subpool[s] aggregations in braidpool ...

Also brings up some organizing of deal with a DC of `ip/24` range of VPS @ 3$ monthly each. 
And if DC can service direct  `ip/24` to `ip/24` route without hops, would make for a very fast subpool with several `ip/24` range[s]  in a virtual local net.

The submit from hasher-location to tunneled VPS will have some hop[s], thereafter node[s] streamed relayed gossips will be without any hop[s].

From hasher-location to VPS expect pings : 
rtt min/avg/max/mdev = 32.210/32.292/32.353/0.052 ms

From hasher-location-VPS to node[s] expect pings : 
rtt min/avg/max/mdev = 0.043/0.052/0.067/0.009 ms

Maybe such a subpool should be a separate braidpool or can be a subpool of a braidpool that also service in the open wild.

**Comment by mcelrath** [comment]
The P2P layer of Braidpool will be focused on communicating globally between Braidpool (and Bitcoin) nodes over the open internet. Braidpool <-> hashing device wire protocols will be left to StratumV2, who is years ahead of us on this topic. Data center network topologies are also out of scope for Braidpool.

As to Sub-Pools, this idea needs fleshing out but is only appropriate if the members of the sub-pool are different miners. If it's all within a same data center under the same administrative control, it's much simpler to just use a Stratum proxy to report only the hashes that satisfy Braidpool's target difficulty and discard the rest (which may have been generated for monitoring purposes).

**Comment by mcelrath** [comment]
Thank you very much for your ideas @s2dd. I suggest you open a more general discussion about intra-datacenter communication and SV2 integration, or sub-pools on the discussion tab on GitHub. 

We're not rejecting your idea but just trying to organize. We don't want our issues list to become as large as Bitcoin core, which is an unmanageable mess.

Personally I want "Issues" to be targets for implementation with very good description that we can use to recruit contributors. Once we get to that point WRT intra-datacenter communication and SV2 integration I think we should make a new issue about it. But @kulpreet is in charge. In the meantime let's discuss. There are lots of things to be decided.
